name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master

env:
  REACT_APP_BACKEND_URL: ${{ secrets.REACT_APP_BACKEND_URL }}
  AZURE_RESOURCE_NAME: "tellerapp"
  DOCKER_IMAGE_NAME: "teller-img"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy with Docker
    steps:
      - uses: actions/checkout@v4
      
      - name: Test Azure Login
        run: |
          echo "${{ secrets.AZURE_CREDENTIALS }}" > creds.json
          az login --service-principal \
            -u $(jq -r .clientId creds.json) \
            -p $(jq -r .clientSecret creds.json) \
            --tenant $(jq -r .tenantId creds.json)
          az account show

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Build Docker image
        run: |
          docker build -t $DOCKER_IMAGE_NAME .
      
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_MOSS_0A5BFEA1E }}
          repo_token: ${{ secrets.GH_TOKEN }}
          app_location: "build"
          output_location: ""
          skip_app_build: true